version: '3.8'

services:
  server-1:
    build:
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: "./conf/config.yml"
    container_name: stateful-server-1
    hostname: stateful-server-1
    environment:
      - SERVER_PORT=:5000
      - SERVER_NAME=stateful-server-1
    ports:
      - "8000:5000"
  server-2:
    build:
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: "./conf/config.yml"
    container_name: stateful-server-2
    hostname: stateful-server-2
    environment:
      - SERVER_PORT=:5000
      - SERVER_NAME=stateful-server-2
    ports:
      - "8001:5000"
  server-3:
    build:
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: "./conf/config.yml"
    container_name: stateful-server-3
    hostname: stateful-server-3
    environment:
      - SERVER_PORT=:5000
      - SERVER_NAME=stateful-server-3
    ports:
      - "8002:5000"